In [12]:
import sys
sys.path.insert(1, '../')
from utils import metrics
import numpy as np

In [13]:
cat_y_true = np.array([0,0,0,0,1,0,0,1,1,1])
cat_y_pred= np.array([0,0,0,0,0,1,1,1,1,1])
lin_y_true = np.array([100, -100, 0, 200])
lin_y_pred = np.array([-100, -100, -100, -100])

# Precision Function

The provided function `precision(y_true, y_pred)` calculates the precision for each class in a multiclass classification problem. 

## Definition of Precision

Precision, also known as the positive predictive value, is a metric that measures the proportion of predicted positives that are actually positive. In binary classification, precision is defined as the number of true positives (TP) over the number of true positives plus the number of false positives (FP). This can be expressed as:

$$
\text{Precision} = \frac{\text{TP}}{\text{TP} + \text{FP}}
$$

True positives are instances of the positive class that the model correctly predicted as positive. False positives are instances of the negative class that the model incorrectly predicted as positive.

## Precision in Multiclass Classification

In the context of multiclass classification, we define precision for each class separately. For a given class, true positives are instances of that class that the model correctly predicted as that class, while false positives are instances of other classes that the model incorrectly predicted as the given class.

This is done by iterating over each class and calculating the precision for that class. The function returns a list of precision values, one for each class.

In the case where there are no predicted instances of a particular class in the test set (`len(total_preds) = 0`), the precision is defined to be 0 for that class.

In [15]:
print(cat_y_true)
print(cat_y_pred)
print(metrics.precision(cat_y_true , cat_y_pred))

[0 0 0 0 1 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1 1]
[0.8 0.6]


# Recall Function

The provided function `recall(y_true, y_pred)` calculates the recall for each class in a multiclass classification problem. 

## Definition of Recall

Recall, also known as sensitivity, hit rate, or true positive rate (TPR), is a metric that measures the proportion of actual positives that are correctly identified as such. In binary classification, recall is defined as the number of true positives (TP) over the number of true positives plus the number of false negatives (FN). This can be expressed as:

$$
\text{Recall} = \frac{\text{TP}}{\text{TP} + \text{FN}}
$$

True positives are instances of the positive class that the model correctly predicted as positive. False negatives are instances of the positive class that the model incorrectly predicted as negative.

## Recall in Multiclass Classification

In the context of multiclass classification, we define recall for each class separately. For a given class, true positives are instances of that class that the model correctly predicted as that class, while false negatives are instances of that class that the model incorrectly predicted as some other class.

This is done by iterating over each class and calculating the recall for that class. The function returns a list of recall values, one for each class.

In the case where there are no true instances of a particular class in the test set (`total_true = 0`), the recall is defined to be 0 for that class.

In [14]:
print(cat_y_true)
print(cat_y_pred)
print(metrics.recall(cat_y_true , cat_y_pred))

[0 0 0 0 1 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1 1]
[0.66666667 0.75      ]


# F1 Score Function

The provided function `f1_score(y_true, y_pred)` calculates the F1 score for each class in a multiclass classification problem.

## Definition of F1 Score

The F1 score is the harmonic mean of precision and recall, and it serves as a balance between these two metrics. An F1 score reaches its best value at 1 (perfect precision and recall) and worst at 0. In binary classification, the F1 score is defined as:

$$
\text{F1 Score} =  2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}
$$

In the context of multiclass classification, we calculate the F1 score for each class separately. For a given class, the F1 score uses the precision and recall for that class.

In the `f1_score` function, the precision and recall for each class are calculated using the previously defined `precision` and `recall` functions. The function then calculates the F1 score for each class, and it returns a list of F1 scores, one for each class.

The `1e-8` in the denominator is a small number added to prevent division by zero when both precision and recall are zero.


In [16]:
print(cat_y_true)
print(cat_y_pred)
print(metrics.f1_score(cat_y_true , cat_y_pred))

[0 0 0 0 1 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1 1]
[0.72727272 0.66666666]
