In [51]:
import sys
sys.path.insert(1, '../')
from utils import metrics
import numpy as np

In [52]:
cat_y_true = np.array([0,0,0,0,1,0,0,1,1,1])
cat_y_pred= np.array([0,0,0,0,0,1,1,1,1,1])
lin_y_true = np.array([100, -100, 0, 200])
lin_y_pred = np.array([-100, -100, -100, -100])

# Compute Measurements Function

Function `compute_measurements(conf_matrix)` calculates the True Positives (TP), False Positives (FP), False Negatives (FN), and True Negatives (TN) for each class in a multiclass classification problem. These measurements are fundamental in understanding the performance of a classification model.

## Definition of TP, FP, FN, TN

- True Positives (TP): These are the correctly predicted positive values which means that the value of actual class is yes and the value of predicted class is also yes.
- True Negatives (TN): These are the correctly predicted negative values which means that the value of actual class is no and value of predicted class is also no.
- False Positives (FP): When actual class is no and predicted class is yes.
- False Negatives (FN): When actual class is yes but predicted class in no.

## Computation

In the `compute_measurements` function, the measurements are calculated as follows:

- TP: The diagonal elements of the confusion matrix.
- FP: The sum of the elements in the column for the class, excluding the TP.
- FN: The sum of the elements in the row for the class, excluding the TP.
- TN: The sum of all elements in the confusion matrix, excluding the elements in the row and column for the class.

The function returns these measurements as numpy arrays.

In [53]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(cat_y_true, cat_y_pred)
metrics.compute_measurements(conf_matrix)

(array([4, 3], dtype=int64),
 array([1, 2], dtype=int64),
 array([2, 1], dtype=int64),
 array([3, 4], dtype=int64))

# Precision Function

Function `precision(y_true, y_pred)` calculates the precision for each class in a multiclass classification problem. 

## Definition of Precision

Precision, also known as the positive predictive value, is a metric that measures the proportion of predicted positives that are actually positive. In binary classification, precision is defined as the number of true positives (TP) over the number of true positives plus the number of false positives (FP). This can be expressed as:

$$
\text{Precision} = \frac{\text{TP}}{\text{TP} + \text{FP}}
$$

True positives are instances of the positive class that the model correctly predicted as positive. False positives are instances of the negative class that the model incorrectly predicted as positive.

## Precision in Multiclass Classification

In the context of multiclass classification, precision is defined for each class separately. For a given class, true positives are instances of that class that the model correctly predicted as that class, while false positives are instances of other classes that the model incorrectly predicted as the given class.

This is done by iterating over each class and calculating the precision for that class. The function returns a list of precision values, one for each class.


In [54]:
print(cat_y_true)
print(cat_y_pred)
print(metrics.precision(cat_y_true , cat_y_pred))

[0 0 0 0 1 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1 1]
[0.8 0.6]


# Recall Function

Function `recall(y_true, y_pred)` calculates the recall for each class in a multiclass classification problem. 

## Definition of Recall

Recall, also known as sensitivity, hit rate, or true positive rate (TPR), is a metric that measures the proportion of actual positives that are correctly identified as such. In binary classification, recall is defined as the number of true positives (TP) over the number of true positives plus the number of false negatives (FN). This can be expressed as:

$$
\text{Recall} = \frac{\text{TP}}{\text{TP} + \text{FN}}
$$

True positives are instances of the positive class that the model correctly predicted as positive. False negatives are instances of the positive class that the model incorrectly predicted as negative.

## Recall in Multiclass Classification

In the context of multiclass classification,recall is definied for each class separately. For a given class, true positives are instances of that class that the model correctly predicted as that class, while false negatives are instances of that class that the model incorrectly predicted as some other class.

This is done by iterating over each class and calculating the recall for that class. The function returns a list of recall values, one for each class.

In the case where there are no true instances of a particular class in the test set (`total_true = 0`), the recall is defined to be 0 for that class.

In [55]:
print(cat_y_true)
print(cat_y_pred)
print(metrics.recall(cat_y_true , cat_y_pred))

[0 0 0 0 1 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1 1]
[0.66666667 0.75      ]


# F1 Score Function

Function `f1_score(y_true, y_pred)` calculates the F1 score for each class in a multiclass classification problem.

## Definition of F1 Score

The F1 score is the harmonic mean of precision and recall, and it serves as a balance between these two metrics. An F1 score reaches its best value at 1 (perfect precision and recall) and worst at 0. In binary classification, the F1 score is defined as:

$$
\text{F1 Score} =  2 \times \frac{\text{Precision} \times \text{Recall}}{\text{Precision} + \text{Recall}}
$$

In the context of multiclass classification,F1 score is calculated for each class separately. For a given class, the F1 score uses the precision and recall for that class.

In the `f1_score` function, the precision and recall for each class are calculated using the previously defined `precision` and `recall` functions. The function then calculates the F1 score for each class, and it returns a list of F1 scores, one for each class.

The `1e-8` in the denominator is a small number added to prevent division by zero when both precision and recall are zero.


In [56]:
print(cat_y_true)
print(cat_y_pred)
print(metrics.f1_score(cat_y_true , cat_y_pred))

[0 0 0 0 1 0 0 1 1 1]
[0 0 0 0 0 1 1 1 1 1]
[0.72727272 0.66666666]


# Confusion Matrix Function

Function `confusion_matrix(y_true, y_pred, return_perf_measurement=False)` calculates the confusion matrix for a multiclass classification problem. The confusion matrix is a table layout that allows visualization of the performance of an algorithm. Each row of the matrix represents the instances in a predicted class, while each column represents the instances in an actual class (or vice versa). 

## Parameters

- `y_true`: Actual class labels.
- `y_pred`: Predicted class labels.
- `return_perf_measurement`: If True, function also returns performance measurements (True Positives, False Positives, False Negatives, True Negatives). Default is False.

## Returns

- If `return_perf_measurement` is False, the function returns only the confusion matrix.
- If `return_perf_measurement` is True, the function returns a tuple containing the confusion matrix and performance measurements for each class.

In the confusion matrix, the element at the i-th row and j-th column of the matrix indicates the number of instances that belong to the i-th actual class and are predicted as the j-th class.

The function iterates over each unique class and for each class, it calculates the number of instances that belong to that class in the actual labels (`y_true`) and are predicted as each class in the predicted labels (`y_pred`). This is done for every combination of actual and predicted classes to form the confusion matrix.

The function optionally returns the performance measurements (True Positives, False Positives, False Negatives, True Negatives) for each class if `return_perf_measurement` is set to True. This is done by calling the function `compute_measurements(conf_matrix)`.

In [57]:
cat_y_true = [1, 2, 3, 1, 2, 3]
cat_y_pred= [1, 2, 1, 1, 2, 3]
metrics.confusion_matrix(cat_y_true, cat_y_pred)

array([[2., 0., 0.],
       [0., 2., 0.],
       [1., 0., 1.]])

In [58]:
#conf matrix, TP, FP, FN, TN
metrics.confusion_matrix(cat_y_true, cat_y_pred, return_perf_measurement=True)

(array([[2., 0., 0.],
        [0., 2., 0.],
        [1., 0., 1.]]),
 (array([2., 2., 1.]),
  array([1., 0., 0.]),
  array([0., 0., 1.]),
  array([3., 4., 4.])))

# Mean Squared Error Function

Function `mean_squared_error(y_true, y_pred, root=False)` calculates the Mean Squared Error (MSE) or Root Mean Squared Error (RMSE) between the true and predicted values. 

## Definition of MSE and RMSE

- Mean Squared Error (MSE): It is the average of the squared differences between the predicted and actual values. It is a popular metric for regression problems and it is defined as:

$$
\text{MSE} = \frac{1}{n}\sum_{i=1}^{n}(y_{\text{true},i} - y_{\text{pred},i})^2
$$

- Root Mean Squared Error (RMSE): It is the square root of the MSE. It measures the standard deviation of the residuals (prediction errors). Residuals are a measure of how far from the regression line data points are, and RMSE is a measure of how spread out these residuals are.

$$
\text{RMSE} = \sqrt{\text{MSE}}
$$

## Computation

In the `mean_squared_error` function, the MSE is calculated as the mean of the squared differences between `y_true` and `y_pred`. If `root` is set to True, the function returns the RMSE, which is the square root of the MSE.


In [59]:
print(lin_y_true)
print(lin_y_pred)
mse = metrics.mean_squared_error(lin_y_true, lin_y_pred)
rmse = metrics.mean_squared_error(lin_y_true, lin_y_pred, root=True)
print(f'Mean squared error: {mse:.1f}')
print(f'Root mean squared error: {rmse:.1f}')

[ 100 -100    0  200]
[-100 -100 -100 -100]
Mean squared error: 35000.0
Root mean squared error: 187.1


# Mean Absolute Error Function

Function `mean_absolute_error(y_true, y_pred)` calculates the Mean Absolute Error (MAE) between the true and predicted values. 

## Definition of MAE

Mean Absolute Error (MAE) is the average of the absolute differences between the predicted and actual values. It measures the average magnitude of errors in a set of predictions, without considering their direction. It's a popular metric for regression problems and it is defined as:

$$
\text{MAE} = \frac{1}{n}\sum_{i=1}^{n}\left|y_{\text{true},i} - y_{\text{pred},i}\right|
$$

## Computation

In the `mean_absolute_error` function, the MAE is calculated as the mean of the absolute differences between `y_true` and `y_pred`.


In [60]:
print(lin_y_true)
print(lin_y_pred)
mae = metrics.mean_absolute_error(lin_y_true, lin_y_pred)
print(f'Mean absolute error: {mae:.1f}')

[ 100 -100    0  200]
[-100 -100 -100 -100]
Mean absolute error: 150.0
